name: CI

# Триггеры: пуши и PR в main и develop
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1) Синхронизируем код
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Собираем образ по вашему Dockerfile
      - name: Build Docker image
        run: docker build -t otus-multithreaded .

      # 3) Прогоняем PHPUnit внутри контейнера
      - name: Run PHPUnit tests in Docker
        run: docker run --rm otus-multithreaded vendor/bin/phpunit --colors=always
