name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t otus-multithreaded .

      - name: Run PHPUnit inside container
        run: docker run --rm otus-multithreaded vendor/bin/phpunit --colors=always
